# Generated by Django 4.2.10 on 2024-08-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('guid', models.CharField(max_length=36)),
                ('platform', models.IntegerField()),
                ('modified', models.IntegerField()),
                ('fin', models.CharField(blank=True, max_length=100)),
                ('sea', models.BooleanField(default=False)),
                ('tmg', models.BooleanField(default=False)),
                ('efis', models.BooleanField(default=False)),
                ('fnpt', models.IntegerField(default=0)),
                ('make', models.CharField(max_length=100)),
                ('run2', models.BooleanField(default=False)),
                ('class_field', models.IntegerField(default=0)),
                ('model', models.CharField(max_length=100)),
                ('power', models.IntegerField(default=1)),
                ('seats', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('kg5700', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('complex', models.BooleanField(default=False)),
                ('cond_log', models.IntegerField(default=0)),
                ('fav_list', models.BooleanField(default=False)),
                ('category', models.IntegerField(default=0)),
                ('high_perf', models.BooleanField(default=False)),
                ('sub_model', models.CharField(blank=True, max_length=100)),
                ('aerobatic', models.BooleanField(default=False)),
                ('ref_search', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('tailwheel', models.BooleanField(default=False)),
                ('default_app', models.IntegerField(default=0)),
                ('default_log', models.IntegerField(default=0)),
                ('default_ops', models.IntegerField(default=0)),
                ('device_code', models.IntegerField(default=0)),
                ('aircraft_code', models.CharField(max_length=36)),
                ('default_launch', models.IntegerField(default=0)),
                ('record_modified', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PilotLog',
        ),
    ]
